CREATE TABLE IF NOT EXISTS "Users" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "nickname" VARCHAR(255) NOT NULL UNIQUE,
    "global_name" VARCHAR(255),
    "pp" VARCHAR(255),
    "last_connection" TIMESTAMP,
    "mail_address" VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "Games" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "id_user_host" INTEGER NOT NULL,
    "type" VARCHAR(255) NOT NULL,
    "code" VARCHAR(255),
    "date_start_game" TIMESTAMP NOT NULL,
    "date_end_game" TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT fk_game_host
        FOREIGN KEY ("id_user_host")
        REFERENCES "Users" ("id")
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "Events" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "id_game" INTEGER NOT NULL,
    "description" VARCHAR(255),
    "status" SMALLINT NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT fk_event_game
        FOREIGN KEY ("id_game")
        REFERENCES "Games" ("id")
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Invitations" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "id_user" INTEGER NOT NULL,
    "id_event" INTEGER NOT NULL,
    PRIMARY KEY ("id"),
    UNIQUE ("id_user", "id_event"),
    CONSTRAINT fk_invitation_user
        FOREIGN KEY ("id_user")
        REFERENCES "Users" ("id")
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_invitation_event
        FOREIGN KEY ("id_event")
        REFERENCES "Events" ("id")
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);
